[tool.poetry]
name = "foundation"
version = "0.0.0.13"
description = "Python core package for builder"
authors = ["Clement Jambou"]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.23.4"
websocket-client = "^1.7.0"
mypy = "^1.9.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytransform3d = "==1.13.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.3"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
