name: pre-commit

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      SKIP: typescript-check,eslint-check
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
